@startuml

enum ArgumentType {
    INT
    BOOL
    STRING
    TYPE
    NIL
    LABEL
    VAR
}

enum ArgumentInInst {
    VAR
    SYMB
    LABEL
    TYPE
}

enum InstructionFormat {
    MOVE
    CREATEFRAME
    PUSHFRAME
    POPFRAME
    DEFVAR
    CALL
    RETURN
    PUSHS
    POPS
    ADD
    SUB
    MUL
    IDIV
    LT
    GT
    EQ
    AND
    OR
    NOT
    INT2CHAR
    STRI2INT
    READ
    WRITE
    CONCAT
    STRLEN
    GETCHAR
    SETCHAR
    TYPE
    LABEL
    JUMP
    JUMPIFEQ
    JUMPIFNEQ
    EXIT
}

@enduml